language: csharp
env:
  global:
    - ZIP_PASSWORD="gQn337XZBEFxzFuVwzKgc27ehZo7XLz485hh3erqF9"
matrix:
  include:
    - env:
      - PRIMARY_KSPVER="1.4.5"
      - PRIMARY_BIN="14"
      - PRIMARY_DEFS=""
      - SECONDARY_KSPVER="1.3.1"
      - SECONDARY_BIN="13"
      - SECONDARY_DEFS="/p:DefineConstants=KSP13"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq p7zip-full bash openssh-client jq
before_script:
  - echo "Downloading Reference DLLs for KSP $PRIMARY_KSPVER"
  - md $TRAVIS_BUILD_DIR/src/$PRIMARY_BIN
  - wget https://img.spaceball.cf/KSP-$PRIMARY_KSPVER.7z
  - 7za x KSP-$PRIMARY_KSPVER.7z -o$TRAVIS_BUILD_DIR/$PRIMARY_BIN -p$ZIP_PASSWORD
  - echo "Downloading Reference DLLs for KSP $SECONDARY_KSPVER"
  - md $TRAVIS_BUILD_DIR/src/$SECONDARY_BIN
  - wget https://img.spaceball.cf/KSP-$SECONDARY_KSPVER.7z
  - 7za x KSP-$SECONDARY_KSPVER.7z -o$TRAVIS_BUILD_DIR/$SECONDARY_BIN -p$ZIP_PASSWORD
script:
  - cd "$TRAVIS_BUILD_DIR"
  - bash "$TRAVIS_BUILD_DIR/buildscripts/Travis/avc_to_assembly.sh"
  - msbuild $SECONDARY_DEFS Kerbalism.sln /t:Build /p:Configuration=Release 1.3
  - msbuild $PRIMARY_DEFS Kerbalism.sln /t:Build /p:Configuration=Release
after_success:
  - export MOD_VERSION=$(cat $TRAVIS_BUILD_DIR/GameData/Kerbalism/Kerbalism.version | jq '.VERSION.MAJOR').$(cat $TRAVIS_BUILD_DIR/GameData/Kerbalism/Kerbalism.version | jq '.VERSION.MINOR').$(cat $TRAVIS_BUILD_DIR/GameData/Kerbalism/Kerbalism.version | jq '.VERSION.PATCH')
  - bash "$TRAVIS_BUILD_DIR/buildscripts/Travis/avc_version.sh" $PRIMARY_KSPVER "$TRAVIS_BUILD_DIR/GameData/Kerbalism/Kerbalism.version"
  - /bin/cp -rf $TRAVIS_BUILD_DIR/src/$PRIMARY_BIN/obj/Release/KerbalismBootStrap.dll $TRAVIS_BUILD_DIR/GameData/Kerbalism/KerbalismBootStrap.dll
  - /bin/cp -rf $TRAVIS_BUILD_DIR/src/$PRIMARY_BIN/obj/Release/Kerbalism.dll $TRAVIS_BUILD_DIR/GameData/Kerbalism/Kerbalism$PRIMARY_BIN.bin
  - /bin/cp -rf $TRAVIS_BUILD_DIR/src/$SECONDARY_BIN/obj/Release/Kerbalism.dll $TRAVIS_BUILD_DIR/GameData/Kerbalism/Kerbalism$SECONDARY_BIN.bin
  - 7za a "$TRAVIS_BUILD_DIR/Kerbalism-$MOD_VERSION-BUILD$TRAVIS_BUILD_NUMBER.zip" "$TRAVIS_BUILD_DIR/GameData"
  - 7za a "$TRAVIS_BUILD_DIR/Kerbalism-$MOD_VERSION-BUILD$TRAVIS_BUILD_NUMBER.zip" "$TRAVIS_BUILD_DIR/LICENSE"
  - 7za a "$TRAVIS_BUILD_DIR/Kerbalism-$MOD_VERSION-BUILD$TRAVIS_BUILD_NUMBER.zip" "$TRAVIS_BUILD_DIR/CHANGELOG.md"
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_key
  - chmod 400 /tmp/sftp_key
  - ssh-keyscan -H ${SFTP_TARGET} >> ~/.ssh/known_hosts
  - scp -i /tmp/sftp_key "$TRAVIS_BUILD_DIR/Kerbalism-$MOD_VERSION-BUILD$TRAVIS_BUILD_NUMBER.zip" "${SFTP_USER}@${SFTP_TARGET}:/var/www/builds/Kerbalism-$MOD_VERSION-BUILD$TRAVIS_BUILD_NUMBER.zip"
notifications:
  email: false
