language: csharp
solution: Kerbalism.sln
matrix:
  include:
    - env:
      - KSPVER="1.4.4"
    - env:
      - KSPVER="1.3.1"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq p7zip-full bash
before_script:
  - echo "Downloading DLLs for KSP $KSPVER."
  - wget https://img.spaceball.cf/KSP-$KSPVER.7z
  - 7za x KSP-$KSPVER.7z -o$TRAVIS_BUILD_DIR -p$ZIP_PASSWORD
  - 7za x KSP-$KSPVER.7z -o$TRAVIS_BUILD_DIR/src -p$ZIP_PASSWORD
  - bash $TRAVIS_BUILD_DIR/buildscripts/Patches/travis-apply.sh
after_success:
  - /bin/cp -rf $TRAVIS_BUILD_DIR/src/obj/Release/Kerbalism.dll $TRAVIS_BUILD_DIR/GameData/Kerbalism/Kerbalism.dll
  # TODO: Artifact uploading
notifications:
